#!/usr/bin/env bash
set -eou pipefail

#######################################
# 情况一: setup radp bash framework
# Globals:
#   BASH_SOURCE
# Arguments:
#   @ - 命令行所有参数
# Outputs:
#   None
# Returns:
#   None
#######################################
setup_radp_bash_framework_via_source() {
  local radp_bf="$PROJECT_SRC_ROOT"/src/main/shell/bin/radp-bf

  # 自定义用户配置文件目录
  GX_RADP_FW_USER_CONFIG_PATH="$EXAMPLE_SRC_ROOT"/config

  # shellcheck source=../../../main/shell/framework/run.sh
  source "$("$radp_bf" --print-run)" "$@"
}

#######################################
# 情况二: setup radp bash framework
# Globals:
#   BASH_SOURCE
# Arguments:
#   @ - 命令行所有参数
# Outputs:
#   None
# Returns:
#   None
#######################################
setup_radp_bash_framework_via_helper() {
  # 自定义用户配置文件目录
  GX_RADP_FW_USER_CONFIG_PATH="$EXAMPLE_SRC_ROOT"/config

  # shellcheck source=../../../main/shell/framework/run.sh
  source "$(radp-bf --print-run)" "$@"
}

#######################################
# 情况一: 如果你是将 radp-bash-framework 直接放置到工程目录下, 导入框架的方式见 setup_radp_bash_framework_from_source
# 情况二: 如果你提前根据 README.md 安装了 radp-bash-framework, 淡入框架的方式见 setup_radp_bash_framework_via_helper
# 根据情况, 参考对应的方式即可, 这里由于是示例, 列出了所有情况
# Globals:
#   None
# Arguments:
#   1 - 导入框架的方式
# Outputs:
#
# Returns:
#   0 - Success
#######################################
setup_radp_bash_framework() {
  local type=${1:-}
  shift
  case $type in
  source)

    setup_radp_bash_framework_via_source "$@"
    ;;
  *)
    GX_RADP_FW_USER_CONFIG_PATH="$pwd"/config
    setup_radp_bash_framework_via_helper "$@"
    ;;
  esac
  readonly GX_RADP_FW_USER_CONFIG_PATH
}

#######################################
# 如果要使用 radp_bash_framework 只需要按照 setup_radp_bash_framework 便可以完成初始化了
# Globals:
#   GX_RADP_FW_USER_CONFIG_PATH
# Arguments:
#   @ - 命令行所有参数
# Outputs:
#   None
# Returns:
#   None
#######################################
main() {
  EXAMPLE_SRC_ROOT=""
  EXAMPLE_SRC_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
  PROJECT_SRC_ROOT="$EXAMPLE_SRC_ROOT"/../../../..
  PROJECT_SRC_ROOT=$(cd -P -- "$PROJECT_SRC_ROOT" && pwd)

  setup_radp_bash_framework "source" "$@"
}

declare -g GX_RADP_FW_USER_CONFIG_PATH=${GX_RADP_FW_USER_CONFIG_PATH:-}
main "$@"
