#!/usr/bin/env bash
set -eou pipefail

#######################################
# 导入 radp bash framework
# Globals:
#   BASH_SOURCE
# Arguments:
#   @ - 命令行所有参数
# Outputs:
#   None
# Returns:
#   None
#######################################
setup_radp_bash_framework() {
  local pwd
  pwd=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
  GX_RADP_USER_CONFIG_PATH="$pwd"/config
  readonly GX_RADP_USER_CONFIG_PATH

  # shellcheck source=../../../main/shell/framework/run.sh
  source "$pwd"/../../../main/shell/framework/run.sh "$@"
}

#######################################
# 如果要使用 radp_bash_framework 只需要按照 setup_radp_bash_framework 便可以完成初始化了
# Globals:
#   GX_RADP_USER_CONFIG_PATH
# Arguments:
#   @ - 命令行所有参数
# Outputs:
#   None
# Returns:
#   None
#######################################
main() {
  setup_radp_bash_framework "$@"
}

declare -g GX_RADP_USER_CONFIG_PATH=${GX_RADP_USER_CONFIG_PATH:-}
main "$@"
