#!/usr/bin/env bash
# shellcheck disable=SC2317
#######################################
# radp-bf completion script generation
# Generates bash/zsh completion scripts for the radp-bf CLI tool
#######################################

#######################################
# Generate shell completion script for radp-bf
# Arguments:
#   $1 - Shell type: bash or zsh
# Outputs:
#   Completion script to stdout
#######################################
radp_cli_bf_completion_generate() {
  local shell="${1:-}"

  case "$shell" in
  bash)
    __radp_cli_bf_completion_bash
    ;;
  zsh)
    __radp_cli_bf_completion_zsh
    ;;
  "")
    radp_log_error "Shell type required (bash or zsh)"
    echo "Usage: radp-bf completion <bash|zsh>" >&2
    return 1
    ;;
  *)
    radp_log_error "Unknown shell type: $shell"
    echo "Supported shells: bash, zsh" >&2
    return 1
    ;;
  esac
}

#######################################
# Generate bash completion script
#######################################
__radp_cli_bf_completion_bash() {
  cat <<'BASH_COMPLETION'
# radp-bf bash completion
# Generated by radp-bash-framework

_radp_bf() {
    local cur prev words cword

    # Initialize completion variables
    if type _init_completion &>/dev/null; then
        _init_completion || return
    else
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    fi

    local commands="new upgrade path resolve-root version help completion self-update"
    local global_opts="-v --verbose --debug -h --help"

    # Handle command-specific completions
    case "${words[1]}" in
        new)
            # new <name> [dir]
            # First arg: project name (no completion)
            # Second arg: directory completion
            if [[ $cword -eq 3 ]]; then
                if type _filedir &>/dev/null; then
                    _filedir -d
                else
                    COMPREPLY=($(compgen -d -- "$cur"))
                fi
            fi
            return
            ;;
        upgrade)
            local upgrade_opts="--dry-run --force --diff"
            local components="entry ide gitignore version workflows all"

            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "$upgrade_opts" -- "$cur"))
                    return
                    ;;
            esac

            # First positional arg: directory
            # Subsequent args: components
            local pos_count=0
            local i
            for ((i = 2; i < cword; i++)); do
                case "${words[i]}" in
                    -*) ;; # skip options
                    *) ((pos_count++)) ;;
                esac
            done

            if [[ $pos_count -eq 0 ]]; then
                # First positional: directory
                if type _filedir &>/dev/null; then
                    _filedir -d
                else
                    COMPREPLY=($(compgen -d -- "$cur"))
                fi
            else
                # Subsequent: components
                COMPREPLY=($(compgen -W "$components" -- "$cur"))
            fi
            return
            ;;
        path)
            COMPREPLY=($(compgen -W "init launcher root" -- "$cur"))
            return
            ;;
        resolve-root)
            # File/script path completion
            if type _filedir &>/dev/null; then
                _filedir
            else
                COMPREPLY=($(compgen -f -- "$cur"))
            fi
            return
            ;;
        completion)
            COMPREPLY=($(compgen -W "bash zsh" -- "$cur"))
            return
            ;;
        version|help)
            # No arguments
            return
            ;;
        self-update)
            local selfupdate_opts="--check --force --full --standard"
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "$selfupdate_opts" -- "$cur"))
                    ;;
            esac
            return
            ;;
    esac

    # Top-level completion (no command selected yet)
    case "$cur" in
        -*)
            COMPREPLY=($(compgen -W "$global_opts" -- "$cur"))
            ;;
        *)
            COMPREPLY=($(compgen -W "$commands" -- "$cur"))
            ;;
    esac
}

complete -F _radp_bf radp-bf
BASH_COMPLETION
}

#######################################
# Generate zsh completion script
#######################################
__radp_cli_bf_completion_zsh() {
  cat <<'ZSH_COMPLETION'
#compdef radp-bf
# radp-bf zsh completion
# Generated by radp-bash-framework

# Subcommand functions
_radp_bf_new() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1:project name:' \
        '2:directory:_files -/'
}

_radp_bf_upgrade() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '--dry-run[Show changes without applying]' \
        '--force[Overwrite user-modified files]' \
        '--diff[Show file differences]' \
        '1:directory:_files -/' \
        '*:component:(entry ide gitignore version workflows all)'
}

_radp_bf_path() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1:path name:(init launcher root)'
}

_radp_bf_resolve_root() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1:script path:_files'
}

_radp_bf_completion() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1:shell:(bash zsh)'
}

_radp_bf_version() {
    _arguments -s '(-h --help)'{-h,--help}'[Show help]'
}

_radp_bf_help() {
    _arguments -s '(-h --help)'{-h,--help}'[Show help]'
}

_radp_bf_self_update() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '--check[Check for updates without installing]' \
        '--force[Force update even if already at latest]' \
        '--full[Update to full version with bundled deps]' \
        '--standard[Update to standard version]'
}

# Main completion function
_radp_bf() {
    local -a commands=(
        'new:Create a new CLI project'
        'upgrade:Upgrade existing project scaffold'
        'path:Print framework path'
        'resolve-root:Resolve project root from script'
        'version:Show framework version'
        'help:Show help'
        'completion:Generate shell completion script'
        'self-update:Update radp-bf (portable only)'
    )

    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-v --verbose)'{-v,--verbose}'[Enable verbose output]' \
        '--debug[Enable debug output]' \
        '1: :->command' \
        '*:: :->args'

    case "$state" in
        command)
            _describe -t commands 'command' commands
            ;;
        args)
            local cmd_func="_radp_bf_${words[1]//-/_}"
            if (( $+functions[$cmd_func] )); then
                $cmd_func
            else
                _files
            fi
            ;;
    esac
}

_radp_bf "$@"
ZSH_COMPLETION
}
