#!/usr/bin/env bash
set -e

__fw_setup_completion() {
  # shellcheck source=./cache/completion_hint.sh
  cat >"$gr_fw_cached_completion_hint_file" <<'EOF'
#!/usr/bin/env bash
set -e

########################################################################################################################
###
# Completion hint (auto-generated by radp-bash-framework)
# 此文件为框架自动生成，请勿手动编辑
########################################################################################################################
__main() {
EOF

  # fw
  if [[ -d "$gr_fw_context_libs_path" ]]; then
    local -a fw_libs=()
    mapfile -t fw_libs < <(find "$gr_fw_context_libs_path" -type f -name "*.sh" | sort -t '_' -k 1,1n)
    local fw_lib
    printf '\n  # user config\n' >>"$gr_fw_cached_completion_hint_file"
    for fw_lib in "${fw_libs[@]}"; do
      printf '  # shellcheck source=%s\n' "$fw_lib" >>"$gr_fw_cached_completion_hint_file"
    done
  fi

  # user
  printf '\n  # user config\n' >>"$gr_fw_cached_completion_hint_file"
  printf '  # shellcheck source=%s\n\n' "$gr_fw_user_config_file" >>"$gr_fw_cached_completion_hint_file"
  if [[ -d "$gr_radp_fw_user_lib_path" ]]; then
    local -a user_libs=()
    mapfile -t user_libs < <(find "$gr_radp_fw_user_lib_path" -type f -name "*.sh" | sort -t '_' -k 1,1n)

    printf '  # user lib\n' >>"$gr_fw_cached_completion_hint_file"
    local user_lib
    for user_lib in "${user_libs[@]}"; do
      printf '  # shellcheck source=%s\n' "$user_lib" >>"$gr_fw_cached_completion_hint_file"
    done
  fi

  cat >>"$gr_fw_cached_completion_hint_file" <<'EOF'
  :
}

__main
EOF

  if [[ -d "$gr_fw_user_config_path" ]]; then
    cp "$gr_fw_cached_completion_hint_file" "$gr_fw_user_completion_file"
  fi
}

__main() {
  __fw_setup_completion
}

#----------------------------------------------------------------------------------------------------------------------#
declare -gr gr_fw_cached_completion_hint_file="$gr_fw_context_cache_path"/completion_hint.sh
declare -gr gr_fw_user_completion_file="$gr_fw_user_config_path"/completion.sh
__main
