#!/usr/bin/env bash
set -e

#######################################
# Generate IDE completion hints file for user project
# This file enables BashSupport Pro to provide code completion
# for framework functions, framework variables, user variables, and user libs
#
# The generated file uses absolute paths (machine-specific)
# and should be added to .gitignore
#
# Globals:
#   gr_fw_context_vars_path - framework vars directory
#   gr_fw_config_file - framework config file
#   gr_fw_context_libs_path - framework libs directory
#   gr_fw_user_config_file - user config file (contains gr_radp_extend_* vars)
#   gr_radp_fw_user_lib_path - user libs directory
#   gr_fw_user_config_path - user config directory
# Outputs:
#   Writes completion.sh to user config directory
#######################################
__fw_setup_completion() {
  # Only generate if user config directory exists
  [[ ! -d "$gr_fw_user_config_path" ]] && return 0

  local completion_file="$gr_fw_user_config_path/completion.sh"

  cat >"$completion_file" <<'EOF'
#!/usr/bin/env bash
set -e

########################################################################################################################
###
# IDE Navigation Hints (auto-generated by radp-bash-framework)
# This file provides code completion for BashSupport Pro IDE plugin
#
# DO NOT commit this file to git - add to .gitignore
# Regenerate by running your CLI tool once (e.g., homelabctl --help)
#
# Contents:
#   - Framework global variables (gr_fw_*, gr_radp_fw_*)
#   - Framework library functions (radp_*)
#   - User global variables (gr_radp_extend_*)
#   - User library functions
########################################################################################################################
__ide_hints() {
EOF

  # 1. Framework global vars
  printf '\n  # Framework global vars\n' >>"$completion_file"
  printf '  # shellcheck source=%s\n' "$gr_fw_context_vars_path/global_vars.sh" >>"$completion_file"
  printf '  # shellcheck source=%s\n' "$gr_fw_config_file" >>"$completion_file"

  # 2. Framework libs
  if [[ -d "$gr_fw_context_libs_path" ]]; then
    printf '\n  # Framework libs\n' >>"$completion_file"
    local -a fw_libs=()
    mapfile -t fw_libs < <(find "$gr_fw_context_libs_path" -type f -name "*.sh" | sort -t '_' -k 1,1n)
    local fw_lib
    for fw_lib in "${fw_libs[@]}"; do
      printf '  # shellcheck source=%s\n' "$fw_lib" >>"$completion_file"
    done
  fi

  # 3. User config file (contains gr_radp_extend_* vars)
  if [[ -f "$gr_fw_user_config_file" ]]; then
    printf '\n  # User config (user global vars: gr_radp_extend_*)\n' >>"$completion_file"
    printf '  # shellcheck source=%s\n' "$gr_fw_user_config_file" >>"$completion_file"
  fi

  # 4. User libs
  if [[ -d "$gr_radp_fw_user_lib_path" ]]; then
    printf '\n  # User libs\n' >>"$completion_file"
    local -a user_libs=()
    mapfile -t user_libs < <(find "$gr_radp_fw_user_lib_path" -type f -name "*.sh" | sort -t '_' -k 1,1n)
    local user_lib
    for user_lib in "${user_libs[@]}"; do
      printf '  # shellcheck source=%s\n' "$user_lib" >>"$completion_file"
    done
  fi

  cat >>"$completion_file" <<'EOF'
  :
}

__ide_hints
EOF
}

__main() {
  __fw_setup_completion
}

__main
