#!/usr/bin/env bash
set -e

#######################################
# 生成静态 hint 文件
# 用于 IDE/ShellCheck 追踪用户 completion 文件
# Globals:
#   None
# Arguments:
#   1 - completion hint file path
# Outputs:
#   None (写入 hint 文件)
# Returns:
#   0 - Success
#######################################
__fw_create_cached_completion_hint_file() {
  local hint_file=${1:?}
  local completion_file=${2:?}
  if [[ ! -f "$hint_file" ]]; then
    local dir
    dir="$(dirname "$hint_file")"
    [[ ! -d "$dir" ]] && mkdir -p "$dir"
    touch "$hint_file" || radp_log_warn "Failed to create dynamic completion hint file '$hint_file'"
  fi

  cat >"$hint_file" <<EOF
#!/usr/bin/env bash
set -e

# shellcheck source=$completion_file
__fw_source_scripts "$completion_file"
EOF
}

__fw_setup_fw_completion() {
  # shellcheck source=./cache/completion.fw.hint.sh
  cat >"$gr_fw_cached_fw_completion_file" <<'EOF'
#!/usr/bin/env bash
set -e

########################################################################################################################
###
# Framework completion (auto-generated by radp-bash-framework)
# 此文件为框架自动生成，请勿手动编辑
########################################################################################################################

__main() {
  # fw libs

EOF

  if [[ -d "$gr_fw_context_libs_path" ]]; then
    local -a fw_libs=()
    mapfile -t fw_libs < <(find "$gr_fw_context_libs_path" -type f -name "*.sh" | sort -t '_' -k 1,1n)

    local fw_lib
    for fw_lib in "${fw_libs[@]}"; do
      printf '  # shellcheck source=%s\n' "$fw_lib" >>"$gr_fw_cached_fw_completion_file"
    done
  fi

  cat >>"$gr_fw_cached_fw_completion_file" <<'EOF'
  :
}

__main
EOF
}

#######################################
# 生成用户 completion 文件及其 hint 文件
# Globals:
#   gr_fw_user_config_path
#   gr_fw_user_config_file
#   gr_fw_user_completion_file
#   gr_fw_user_completion_hint_file
#   gr_radp_fw_user_lib_path
# Arguments:
#   None
# Outputs:
#   None (写入 completion 与 hint 文件)
# Returns:
#   0 - Success
#######################################
__fw_setup_user_completion() {
  # shellcheck source=./cache/completion.user.hint.sh
  __fw_create_cached_completion_hint_file "$gr_fw_cached_user_completion_hint_file" "$gr_fw_user_completion_file"

  # 如果没有用户配置目录, 也就没有必要去创建 user completion file 了
  if [[ ! -d "$gr_fw_user_config_path" ]]; then
    return 0
  fi
  cat >"$gr_fw_user_completion_file" <<'EOF'
#!/usr/bin/env bash
set -e

########################################################################################################################
###
# User completion (auto-generated by radp-bash-framework)
# 此文件为框架自动生成，请勿手动编辑
########################################################################################################################

__main() {
  # user config
EOF

  printf '  # shellcheck source=%s\n\n' "$gr_fw_user_config_file" >>"$gr_fw_user_completion_file"
  printf '  # user lib\n' >>"$gr_fw_user_completion_file"

  if [[ -d "$gr_radp_fw_user_lib_path" ]]; then
    local -a fw_libs=()
    mapfile -t fw_libs < <(find "$gr_radp_fw_user_lib_path" -type f -name "*.sh" | sort -t '_' -k 1,1n)

    local fw_lib
    for fw_lib in "${fw_libs[@]}"; do
      printf '  # shellcheck source=%s\n' "$fw_lib" >>"$gr_fw_user_completion_file"
    done
  fi

  cat >>"$gr_fw_user_completion_file" <<'EOF'
  :
}

__main
EOF
}

__main() {
  __fw_setup_fw_completion
  __fw_setup_user_completion
}

#----------------------------------------------------------------------------------------------------------------------#
declare -gr gr_fw_cached_fw_completion_file="$gr_fw_context_cache_path"/completion.fw.hint.sh
declare -gr gr_fw_cached_user_completion_hint_file="$gr_fw_context_cache_path"/completion.user.hint.sh
declare -gr gr_fw_user_completion_file="$gr_fw_user_config_path"/completion.sh
__main
