#!/usr/bin/env bash
set -e

__fw_setup_user_completion_hint() {
  # shellcheck source=./cache/completion.user.hint.sh
  cat >"$gr_fw_user_completion_hint_file" <<EOF
#!/usr/bin/env bash
set -e

# shellcheck source=$gr_fw_user_completion_file
__fw_source_scripts "$gr_fw_user_completion_file"
EOF
}

__fw_setup_user_completion() {
  if [[ ! -d "$gr_fw_user_config_path" ]]; then
    return 0
  fi

  __fw_setup_user_completion_hint

  cat >"$gr_fw_user_completion_file" <<'EOF'
set -e

########################################################################################################################
###
# User completion (auto-generated by radp-bash-framework)
# 此文件为框架自动生成，请勿手动编辑
########################################################################################################################

__main() {
  # user config
EOF

  printf '  # shellcheck source=%s\n\n' "$gr_fw_user_config_file" >>"$gr_fw_user_completion_file"
  printf '  # user lib\n' >>"$gr_fw_user_completion_file"

  if [[ -d "$gr_radp_fw_user_lib_path" ]]; then
    local -a user_libs=()
    mapfile -t user_libs < <(find "$gr_radp_fw_user_lib_path" -type f -name "*.sh" | sort -t '_' -k 1,1n)

    local user_lib
    for user_lib in "${user_libs[@]}"; do
      printf '  # shellcheck source=%s\n' "$user_lib" >>"$gr_fw_user_completion_file"
    done
  fi

  cat >>"$gr_fw_user_completion_file" <<'EOF'
  :
}

__main
EOF
}

__main() {
  __fw_setup_user_completion
}

#----------------------------------------------------------------------------------------------------------------------#
declare -gr gr_fw_user_completion_file="$gr_fw_user_config_path"/completion.sh
declare -gr gr_fw_user_completion_hint_file="$gr_fw_context_cache_path"/completion.user.hint.sh
__main
